### PR TITLE
[2.x] Add unsetCache method

### PR DESCRIPTION
**Pull request by antonkomarev**
New method encapsulates cleanup logic in separate method.

### CODE REVIEW

**Comment by Flyrell** [comment]
Might be worth to write a test for it if you have some spare time.

**Comment by antonkomarev** [comment]
@Flyrell sorry, I have real problems with spare time right now. Working hard to launch closed beta of the new startup project until 2020.

**Comment by Flyrell** [comment]
@antonkomarev Sure, I guess we're both in the same place 😄 I will try to write them when I have some time.

**Comment by Flyrell** [comment]
Closing and moving it to #42.

**Pull request closed without merging**
