### PR TITLE
v2.0.0-beta.2 | Typescript support, General bug fixes and more...

### PR DESCRIPTION
**Pull request by Flyrell**
Changes:
- Typescript support,
- Possibility to ignore interceptor for specific calls,
- [Bug fix] Stalled requests are now cancelled when refreshing fails,
- [Bug fix] Fixed issues when using instance created by axios.create()

### CODE REVIEW

**Comment by julienkosinski** [comment]
I have tested this beta version to use an axios instance. I works way better than before. Thanks! :)

**Comment by Flyrell** [comment]
This should now also prevent the interceptor from moving in the interceptors' stack while the refreshing is done.

**Comment by brammitch** [comment]
Thanks for this library! I'm testing it in a TypeScript project that uses create-react-app. Everything works great except for the TypeScript support. I'm getting an error in my compiler:

> Could not find a declaration file for module 'axios-auth-refresh'. 'c:/.../node_modules/axios-auth-refresh/dist/index.min.js' implicitly has an 'any' type.
> Try `npm install @types/axios-auth-refresh` if it exists or add a new declaration (.d.ts) file containing 'declare module 'axios-auth-refresh';`

I created an dummy file with `declare module 'axios-auth-refresh';` in it just so it would compile.

**Comment by israelKusayev** [comment]
Is it ready?

**Comment by Flyrell** [comment]
@brammitch It should be published by now. Sorry it took so long, I completely forgot about it. It was just missing the `types` entry in package.json file.

@israelKusayev Hi, it hasn't been tested completely, yet. Maybe you can help me with that. It should be working, but I want to know for sure as a lot of people use it now.

**Comment by israelKusayev** [comment]
@Flyrell I tested it in my project  [client](https://github.com/Mithazkim/Mithazkim-Client), [server](https://github.com/Mithazkim/Mithazkim-Server)  and it works perfect !!

**Comment by Flyrell** [comment]
I guess it's safe to say the beta tests are complete. In case of any bugs we can still roll back to using v1.x or fix them on the go. Thank you all for helping out.

**Pull request merged**
