### PR TITLE
Adding option to decide whether to attempt refresh

### PR DESCRIPTION
**Pull request by mjsarfatti**
The API might return 401 on login attempt. In this case we need to be able to reject the Axios Promise immediately and tell the user their username/password are incorrect, rather than attempting a refresh.

Use case:

```js
// Function that will be called to determine whether to attempt refresh
const retryAuthCondition = () => !!localStorage.getItem('access_token');

// Function that will be called to refresh authorization
const refreshAuthLogic = () =>
  axios.post('auth/refresh').then(response => {
    localStorage.setItem('access_token', response.data.access_token);
    return Promise.resolve();
  });

// Instantiate the interceptor (you can chain it as it returns the axios instance)
createAuthRefreshInterceptor(axios, refreshAuthLogic, retryAuthCondition);
```

### CODE REVIEW

**Comment by Flyrell** [comment]
I'm not sure if that's the thing for an interceptor only.
What would be the difference between the 401 response from expiring token and the one from log in, if the token is always present? This would make sense if the request object can have some kind of custom data (like I proposed in [#1890](https://github.com/axios/axios/issues/1890)), so we can easily differentiate them.

Your proposal is not bad, but I have a feeling that it would lead to some unexpected bugs. 
I'm surely willing to discuss it more if you have a feeling I'm not right 👍

**Comment by mjsarfatti** [comment]
In my case, I have two situations where I don't want to run the refresh request. I understand it might be done in a different way, so I'm open to suggesstions if you think a different approach is best altogether.

**Case 1**

The backend library I'm using returns 401 both for an attempt to login with wrong credentials (request sent without *access_token*), and for a request with an expired *access_token.*

In the second case I want to try to refresh the token right away, and re-run the original request. All good here.

In the first case, instead, I want to return right away and show a "Wrong username or password" message to the user. If I run the _refresh_ request right away I can't access the error message of the _login_ request, and I can't understand if what went wrong was a wrong password, a non-existing user, or some other error.

In addition to this, my backend library returns a 500 status code on a failed _refresh_. That's definitely a bug with the library, but I think it highlights an edge case.

**Case 2**

When I click **logout** from my app, a request is made with the _access_token_ to invalidate it.

But here is an edge case: I might leave a tab open long enough for the access and refresh token to expire. Or maybe the access token gets blacklisted server-side because the user is suspended. Then I come back to my computer and click "logout". The request fails because the token is no longer valid, but as far as the logout procedure goes, that's a success! It means the localStorage is not holding a valid token, so I can delete it and show the guest routes in my frontend app.

Again, if on failure I immediately run the _refresh_, I can detect precisely what just happened.

And again, it might also be solved server-side by returning 200 if I _logout_ with an already invalid token.

Thoughts?

**Comment by Flyrell** [comment]
I understood the use-case right away as I'm having problems with this too.
I'm just not sure about the current requests/response differentiation as you need to differentiate the calls based on URL right now. I guess there's no other approach to do it.

That's why I think it might lead to numerous bugs with URL matching etc. These are not critical, but it might be hard to debug them. I really appreciate the contribution, but I think I'll wait for the bug to get more attention or for the axios to implement something that would make calls differentiation easier.

If you're interested, in my case I created second axios instance which I'm using for calls that I don't want the interceptor to run for.

**Comment by mjsarfatti** [comment]
Oh, yeah I see your point on how URLs might be weak. 

I'll run my fork on my project since it's a small one, but yeah creating a second axios instance would also work well 👍

**Comment by Flyrell** [comment]
@mjsarfatti This should be now possible in #27. It's still in beta (we need some beta testers if you're interested). Hope you'll enjoy it.

**Comment by mjsarfatti** [comment]
Great to know! Will probably try it in about a month or so on a new app!

**Pull request closed without merging**
