### PR TITLE
fix issue #13

### PR DESCRIPTION
**Pull request by suweya**

### CODE REVIEW

**Comment by Flyrell** [comment]
Looking good @suweya. Thanks.

**Comment by naji247** [comment]
Can we get this merged?

**Comment by Flyrell** [comment]
Should be fixed in #25 alongside typescript support and unit tests. Will test and give you a feedback. In case you want to speed things up, I'd be more than happy if you can also test it. 
Thank you for you contribution!

**Comment by Flyrell** [comment]
Fixed in #27. Please, give it a try before I publish it as latest release (it's in beta now). 

```
npm install axios-auth-refresh@beta --save
```

**Pull request closed without merging**
